# Generated by Django 4.2.13 on 2024-07-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_exam', models.DateField(verbose_name='Дата зачета')),
                ('name_intern', models.CharField(max_length=60, verbose_name='Фамилия Имя стажера')),
                ('cc', models.CharField(choices=[('КЦ1', 'КЦ1'), ('КЦ2', 'КЦ2'), ('КЦ3', 'КЦ3')], max_length=10, verbose_name='КЦ')),
                ('time_exam', models.TimeField(blank=True, default='00:00', verbose_name='Время зачета')),
                ('name_examiner', models.CharField(blank=True, choices=[('Иванов', 'Иванов'), ('Петров', 'Петров'), ('Васечкин', 'Васечкин')], max_length=60, verbose_name='ФИ сотрудника')),
                ('result_exam', models.CharField(blank=True, choices=[('Не допущен', 'Не допущен'), ('Допущен', 'Допущен'), ('Неявка', 'Неявка'), ('Отмена', 'Отмена'), ('Не состоялось', 'Не состоялось')], default='', max_length=25, verbose_name='Результат')),
                ('comment_exam', models.TextField(blank=True, max_length=2000, verbose_name='комментарий')),
            ],
        ),
    ]
